### ISSUE TITLE
Display lights up but nothing is on it

### ISSUE THREAD

**Issue by kkaiser1952** [adafruit/Adafruit-PiTFT-Helper#9]
I followed all the instructions very carefully and all the scripts worked just fine. Then I did the sudo reboot but I don't get anything on the display. It stays lit but nothing else. I'm also curios why it updates /boot/config.txt every time you launch sudo adafruit-pitft-helper -t 28r when all its going to do is then ask you to edit the dupe sections out.
I'm pretty new so forgive the ignorance I just want to get the display working.

Thanks.

**Comment by brennen** [comment]
> I'm also curios why it updates /boot/config.txt every time you launch sudo adafruit-pitft-helper -t 28r when all its going to do is then ask you to edit the dupe sections out.

Did you install the script and our kernel from `apt.adafruit.com`, or download and run `adafruit-pitft-helper` from this repository?

> I'm also curios why it updates /boot/config.txt every time you launch sudo adafruit-pitft-helper -t 28r when all its going to do is then ask you to edit the dupe sections out.

Mostly I got lazy about making it replace the previous section. :)

This has come up a few times lately; it's on my short list to make it replace previous sections instead of just appending to the file.

**Comment by kkaiser1952** [comment]
I didn’t want to download the image so I used the scripts the curl then the -help -t 28r thing. BTW the part where you say it could take 20 minutes didn’t even take 20 seconds. It was very quick.

**Comment by ladyada** [comment]
i do recommend burning the full image if only because you'll know if its the hardware or not :)

**Comment by kkaiser1952** [comment]
OK, but I’m not exactly sure what that means. Can you point me at the instructions.

Thanks man.

**Comment by ladyada** [comment]
https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/easy-install#ready-to-go-image

**Comment by kkaiser1952** [comment]
Strike three. I’m afraid it still lights up but nothing is on it.
Tell me you have yet another idea. Please!

**Comment by ladyada** [comment]
sounds like its time to post to the adafruit forums: forums.adafruit.com - thats where we handle tech support :)

**Comment by whoisjake** [comment]
For the record... I was using the burned image since I bought a 1601 and very recently (maybe 2 weeks ago) ran into the same issue where it only took a few seconds to install and only showed white on the screen... It was working fine with previously used burned images, but not so much now...

Trying again today with latest changes to deb package

**Comment by whoisjake** [comment]
Tried the new instructions introduced by commit: 7cc7e09114b9f43d01ebbd6dd2eebb29a3325d75

Worked this time around!
